#!/bin/sh
# Measure per-model prompt-cache effectiveness from the audit trail -> model_cache.yaml
#
# Prompt caching happens automatically provider-side; we send no cache_control. What differs is
# whether a given model caches AT ALL. Measured 2026-07-31: free-pickle 99.6%, free-deepseek
# 96.2%, zai-52 76.6% — but free-north 0% across 28.35M prompt tokens, and it is the CODE-tier
# default. A model that cannot cache re-runs prefill over the whole payload every turn, which
# costs nothing on a free lane but costs LATENCY on every single request.
#
# The router reads this file fresh per request and prefers a caching model for LARGE payloads
# only (see order_tier). Missing file or thin data => fail open, no penalty.
#
# Usage: sh scripts/cache_audit.sh   (cheap: one SQL query, no model calls, spends no quota)
set -e
cd "$(dirname "$0")/.."
OUT="model_cache.yaml"
WINDOW="${CACHE_AUDIT_WINDOW:-7 days}"
# Only large payloads say anything: a 200-token request has nothing worth caching, and counting it
# would drag a good model's average down for no reason.
MIN_PROMPT="${CACHE_AUDIT_MIN_PROMPT:-3000}"
# Below this many samples a verdict is noise; those models stay "unknown" and are never penalised.
MIN_SAMPLES="${CACHE_AUDIT_MIN_SAMPLES:-5}"

rows=$(docker exec litellm-db psql -U litellm -d litellm -t -A -F'|' -c "
select coalesce(model_group,'-'),
       count(*),
       round(100.0 * sum(coalesce((metadata->'usage_object'->'prompt_tokens_details'->>'cached_tokens')::bigint,0))
             / nullif(sum(prompt_tokens),0), 1)
from \"LiteLLM_SpendLogs\"
where prompt_tokens > $MIN_PROMPT and \"startTime\" > now() - interval '$WINDOW'
group by 1 having count(*) >= $MIN_SAMPLES;" 2>/dev/null) || {
  echo "   cache audit skipped (no DB reachable) — router fails open"; exit 0; }

{
  printf '# Auto-generated by scripts/cache_audit.sh — do not edit by hand.\n'
  printf '# Per-model prompt-cache hit rate over the last %s (payloads > %s tokens, >= %s samples).\n' \
         "$WINDOW" "$MIN_PROMPT" "$MIN_SAMPLES"
  printf '# Models absent here are UNKNOWN and are never penalised by the router.\n'
  printf 'models:\n'
  echo "$rows" | while IFS='|' read -r alias n pct; do
    [ -z "$alias" ] && continue
    [ -z "$pct" ] && pct=0
    printf '  %s: {hit_pct: %s, samples: %s}\n' "$alias" "$pct" "$n"
  done
} > "$OUT.new"

# Merge: traffic verdicts (fresh) win; `source: probe` rows from the previous file are kept for
# any model traffic said nothing about. Generating straight over $OUT would delete those and
# silently un-demote a model already measured as never caching.
python3 - "$OUT" "$OUT.new" <<'PY' || cp "$OUT.new" "$OUT"
import sys, yaml, os
out, new = sys.argv[1], sys.argv[2]
def load(p):
    return ((yaml.safe_load(open(p)) or {}).get("models") or {}) if os.path.exists(p) else {}
merged = load(new)
for k, v in load(out).items():
    if isinstance(v, dict) and v.get("source") == "probe":
        merged.setdefault(k, v)
with open(out, "w") as f:
    f.write("# Auto-generated by scripts/cache_audit.sh (traffic) + cache probes.\n")
    f.write("# hit_pct = share of prompt tokens served from the provider cache on large payloads.\n")
    f.write("# source: probe = explicit 2-call test for a model with no traffic yet.\n")
    yaml.safe_dump({"models": merged}, f, default_flow_style=True, sort_keys=True)
PY
rm -f "$OUT.new"

echo "wrote $OUT"
printf '%-22s %8s %8s\n' "alias" "hit%" "samples"
printf '%-22s %8s %8s\n' "----------------------" "--------" "--------"
echo "$rows" | while IFS='|' read -r alias n pct; do
  [ -z "$alias" ] && continue
  printf '%-22s %8s %8s\n' "$alias" "${pct:-0}" "$n"
done
