#!/bin/sh
# Install a launchd agent that keeps the box-to-box tunnels up, across reboots, unattended.
#
# Two tunnels, both pointing at the always-on RTX/WSL2 box:
#   127.0.0.1:4142 -> WSL2 :4042   Codex shim (the OTHER ChatGPT subscription) -> cod2-* aliases
#   127.0.0.1:3445 -> WSL2 :3445   opencode serve, for the desktop app's remote session
#
# Why a launchd agent and not the session loop used by install_health_timer.sh: that one has to
# run from this repo, and launchd cannot read ~/Documents (TCC denies it — the reason the health
# refresher is session-scoped). So the maintainer is installed as a SELF-CONTAINED script under
# ~/.local/bin, needing nothing from the repo at runtime.
#
# The agent re-resolves the WSL2 IP on every tick instead of caching it: that address changes on
# each WSL2 reboot and is the single most common reason these tunnels silently stop working.
#
# Usage:  sh scripts/install_tunnel_agent.sh          (idempotent — reinstall to update)
#         launchctl bootout gui/$(id -u)/com.salva.llmr-tunnels     (to remove)
set -e
# Use the ssh_config ALIAS, never user@ip. The key for this peer is bound to the alias with
# IdentitiesOnly, so connecting by IP offers no key at all once ssh-agent is out of the
# picture — which is exactly the situation launchd runs in. The alias also carries
# UseKeychain, which is what lets an agent-less launchd job authenticate at all.
PEER="${LLMR_TUNNEL_PEER:-rtxhost}"
BIN="$HOME/.local/bin/llmr-tunnels.sh"
PLIST="$HOME/Library/LaunchAgents/com.salva.llmr-tunnels.plist"
LABEL="com.salva.llmr-tunnels"
LOG="$HOME/Library/Logs/llmr-tunnels.log"

mkdir -p "$HOME/.local/bin" "$HOME/Library/LaunchAgents" "$HOME/Library/Logs"

cat > "$BIN" <<EOF
#!/bin/sh
# Auto-generated by scripts/install_tunnel_agent.sh — self-contained on purpose (see that script).
PEER="$PEER"
EOF
cat >> "$BIN" <<'EOF'
PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/homebrew/bin
export PATH

# A port that is merely LISTENing proves nothing: a half-dead forwarder keeps the socket open
# while the far end is gone. Probe the service itself and rebuild only when it fails to answer.
alive() { # $1=port $2=path  -> 0 if the far end answers
  curl -s -m 5 -o /dev/null "http://127.0.0.1:$1$2" 2>/dev/null
}

drop() { # $1=port — clear whatever holds it, so the forward can be rebuilt
  P=$(lsof -nP -iTCP:"$1" -sTCP:LISTEN -t 2>/dev/null || true)
  [ -n "$P" ] && kill $P 2>/dev/null || true
}

# WSL2's address changes on every reboot of that box. Always re-read it.
# NB: no 2>/dev/null inside the remote command. The peer's sshd hands it to Windows cmd,
# which does not understand that redirection and fails with 'no se puede encontrar la ruta'.
IP=$(ssh -o ConnectTimeout=10 -o BatchMode=yes -T "$PEER" 'wsl.exe hostname -I || hostname -I' 2>/dev/null | tr -d '\r' | awk '{print $1}')
[ -z "$IP" ] && { echo "$(date '+%F %T') peer unreachable — nothing to do"; exit 0; }

for spec in "4142 4042 /health" "3445 3445 /"; do
  set -- $spec
  LOCAL=$1; REMOTE=$2; PROBE=$3
  if alive "$LOCAL" "$PROBE"; then continue; fi
  drop "$LOCAL"
  ssh -f -N -o ConnectTimeout=15 -o BatchMode=yes -o ExitOnForwardFailure=yes \
      -o ServerAliveInterval=30 -o ServerAliveCountMax=3 \
      -L "$LOCAL:$IP:$REMOTE" "$PEER" 2>/dev/null \
    && echo "$(date '+%F %T') rebuilt :$LOCAL -> $IP:$REMOTE" \
    || echo "$(date '+%F %T') FAILED to build :$LOCAL -> $IP:$REMOTE"
done
EOF
chmod +x "$BIN"

cat > "$PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>$LABEL</string>
  <key>ProgramArguments</key><array><string>/bin/sh</string><string>$BIN</string></array>
  <key>RunAtLoad</key><true/>
  <key>StartInterval</key><integer>60</integer>
  <key>StandardOutPath</key><string>$LOG</string>
  <key>StandardErrorPath</key><string>$LOG</string>
</dict>
</plist>
EOF

launchctl bootout "gui/$(id -u)/$LABEL" 2>/dev/null || true
launchctl bootstrap "gui/$(id -u)" "$PLIST"
launchctl kickstart -k "gui/$(id -u)/$LABEL"

echo "installed $LABEL — checks every 60s, survives reboot"
echo "   maintainer: $BIN"
echo "   log:        $LOG"
